# Generated by Django 3.1.7 on 2021-03-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_exemplo_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='teste',
            field=models.ManyToManyField(to='vendas.Ba'),
        ),
    ]
