# Generated by Django 3.1.7 on 2021-03-29 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20210329_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='teste',
        ),
        migrations.DeleteModel(
            name='Ba',
        ),
    ]
