# Generated by Django 3.1.7 on 2021-03-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_venda_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='email_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='comprovante_venda',
            field=models.FileField(upload_to='comprovante_venda/', verbose_name='Comprovante de Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='numero_venda',
            field=models.IntegerField(verbose_name='Número da Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor total da venda'),
        ),
    ]
